name: Test Docker Build Issue
on: [push]

jobs:
  test-fleet:
    runs-on:
      - codebuild-aws-shr-${{ github.run_id }}-${{ github.run_attempt }}
      - fleet:fleet1
      - image:linux-5.0
      - buildspec-override:true
    steps:
      - uses: actions/checkout@v4
      - run: |
          uname -a
          docker --version
          containerd --version
